buildscript {
    ext {
        compose_version = '1.5.4'
        compose_compiler_version = '1.5.1'
        kotlin_version = '1.9.0'
        nav_version = '2.7.0'
        lifecycle_version = '2.6.2'
        activity_version = '1.7.2'
        retrofit_version = '2.11.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.2.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
